typography_spectrum: 0.3601946833077818
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.40124236000701785
  lightness: 0.28962880303151906
  saturation: 0.08655798947438598
  rhythmicContrast: 0.5374481305480003
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4190425775013864
analytics:
  google: null
  facebook: null
  twitter: null
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/08b2ff08-c2d4-47b3-a4f1-1df5dbffc1c0.png'
name: 'Peruvian Quinoa &amp; Food Futures'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
